### ISSUE TITLE
Where is the command line entrypoint?

### ISSUE THREAD

**Issue by davidfstein** [nickzren/atav#51]
I see in the user guide a reference to an atav.sh file, however, this does not appear to exist in this repo. How do users interact with the cli? Is there some installation process?

**Comment by nickzren** [comment]
Here is full installation process on AWS ec2:
https://github.com/nickzren/atav/tree/master/ec2

It can be done from laptop or PC too.

It required to setup atav-database first.

**Comment by davidfstein** [comment]
Thanks!
